# Copyright (c) Magnon Compute Corporation. All rights reserved.
title = "Magnon Gitleaks Config"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
regexes = [
    '''EXAMPLE_''',
    '''_PLACEHOLDER''',
    '''magnon\.io/''',
]
paths = [
    '''.gitleaks.toml''',
    '''testdata/''',
    '''fixtures/''',
    '''tests/''',
]
